# This site serves a vanity URL for Go packages. It has no ability to serve any
# other content.

baseURL = 'https://endobit.io/'
languageCode = 'en-us'
title = 'endobit'
copyright = "© 2025 endobit; all rights reserved."
theme = ["github.com/markdumay/hugo-theme-vanity"]

[params]
  redirect = true
